import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

const movies = () => {
  return [
    {
      id: 1,
      first_name: "Stuart",
      last_name: "Reder",
      email: "sreder0@cnbc.com",
      gender: "Male",
      ip_address: "41.2.220.117",
    },
    {
      id: 2,
      first_name: "Caspar",
      last_name: "Brigdale",
      email: "cbrigdale1@elegantthemes.com",
      gender: "Male",
      ip_address: "185.44.175.37",
    },
    {
      id: 3,
      first_name: "Billie",
      last_name: "Mellsop",
      email: "bmellsop2@nps.gov",
      gender: "Male",
      ip_address: "92.11.209.189",
    },
    {
      id: 4,
      first_name: "Linnet",
      last_name: "Simonel",
      email: "lsimonel3@google.cn",
      gender: "Female",
      ip_address: "139.118.242.11",
    },
    {
      id: 5,
      first_name: "Paloma",
      last_name: "McGillreich",
      email: "pmcgillreich4@eventbrite.com",
      gender: "Female",
      ip_address: "240.216.216.133",
    },
    {
      id: 6,
      first_name: "Lorita",
      last_name: "Gummie",
      email: "lgummie5@blinklist.com",
      gender: "Female",
      ip_address: "249.43.125.182",
    },
    {
      id: 7,
      first_name: "Gaile",
      last_name: "Oxberry",
      email: "goxberry6@economist.com",
      gender: "Male",
      ip_address: "111.216.64.154",
    },
    {
      id: 8,
      first_name: "Vern",
      last_name: "Maddinon",
      email: "vmaddinon7@cloudflare.com",
      gender: "Male",
      ip_address: "51.208.60.170",
    },
    {
      id: 9,
      first_name: "Dani",
      last_name: "Partner",
      email: "dpartner8@ucoz.com",
      gender: "Female",
      ip_address: "225.199.153.80",
    },
    {
      id: 10,
      first_name: "Esta",
      last_name: "William",
      email: "ewilliam9@ustream.tv",
      gender: "Female",
      ip_address: "120.143.4.186",
    },
    {
      id: 11,
      first_name: "Wandis",
      last_name: "Ezele",
      email: "wezelea@imageshack.us",
      gender: "Female",
      ip_address: "135.1.215.173",
    },
    {
      id: 12,
      first_name: "Way",
      last_name: "Crut",
      email: "wcrutb@bluehost.com",
      gender: "Male",
      ip_address: "129.17.237.167",
    },
    {
      id: 13,
      first_name: "Isaiah",
      last_name: "Decreuze",
      email: "idecreuzec@icio.us",
      gender: "Male",
      ip_address: "240.30.121.175",
    },
    {
      id: 14,
      first_name: "Kipper",
      last_name: "Redmain",
      email: "kredmaind@clickbank.net",
      gender: "Male",
      ip_address: "18.12.154.195",
    },
    {
      id: 15,
      first_name: "Vitoria",
      last_name: "Dartnall",
      email: "vdartnalle@mlb.com",
      gender: "Female",
      ip_address: "84.107.111.100",
    },
    {
      id: 16,
      first_name: "Yehudi",
      last_name: "Le Jean",
      email: "ylejeanf@deliciousdays.com",
      gender: "Male",
      ip_address: "27.2.14.212",
    },
    {
      id: 17,
      first_name: "Berti",
      last_name: "Norledge",
      email: "bnorledgeg@admin.ch",
      gender: "Male",
      ip_address: "80.63.160.155",
    },
    {
      id: 18,
      first_name: "Beale",
      last_name: "Brassill",
      email: "bbrassillh@ftc.gov",
      gender: "Male",
      ip_address: "105.197.181.56",
    },
    {
      id: 19,
      first_name: "Ava",
      last_name: "Rollingson",
      email: "arollingsoni@usnews.com",
      gender: "Female",
      ip_address: "127.26.33.1",
    },
    {
      id: 20,
      first_name: "Tracey",
      last_name: "Doutch",
      email: "tdoutchj@xrea.com",
      gender: "Male",
      ip_address: "118.152.224.84",
    },
    {
      id: 21,
      first_name: "Eveleen",
      last_name: "Barribal",
      email: "ebarribalk@infoseek.co.jp",
      gender: "Female",
      ip_address: "188.0.105.98",
    },
    {
      id: 22,
      first_name: "Dionis",
      last_name: "Blewitt",
      email: "dblewittl@odnoklassniki.ru",
      gender: "Female",
      ip_address: "187.119.8.10",
    },
    {
      id: 23,
      first_name: "Corina",
      last_name: "Coutthart",
      email: "ccoutthartm@github.io",
      gender: "Female",
      ip_address: "220.88.69.210",
    },
    {
      id: 24,
      first_name: "Petey",
      last_name: "Abbes",
      email: "pabbesn@mapy.cz",
      gender: "Male",
      ip_address: "43.10.9.148",
    },
    {
      id: 25,
      first_name: "Mair",
      last_name: "Kydde",
      email: "mkyddeo@phoca.cz",
      gender: "Female",
      ip_address: "81.12.227.228",
    },
    {
      id: 26,
      first_name: "Westbrooke",
      last_name: "Ervine",
      email: "wervinep@meetup.com",
      gender: "Male",
      ip_address: "194.148.15.146",
    },
    {
      id: 27,
      first_name: "Avigdor",
      last_name: "Aspling",
      email: "aasplingq@cisco.com",
      gender: "Male",
      ip_address: "224.236.106.74",
    },
    {
      id: 28,
      first_name: "Bart",
      last_name: "Crinion",
      email: "bcrinionr@nih.gov",
      gender: "Male",
      ip_address: "167.56.195.246",
    },
    {
      id: 29,
      first_name: "Dieter",
      last_name: "Shackelton",
      email: "dshackeltons@wsj.com",
      gender: "Male",
      ip_address: "146.245.76.148",
    },
    {
      id: 30,
      first_name: "Clemmy",
      last_name: "Muddicliffe",
      email: "cmuddicliffet@marketwatch.com",
      gender: "Male",
      ip_address: "247.251.165.78",
    },
    {
      id: 31,
      first_name: "Pacorro",
      last_name: "Rugge",
      email: "pruggeu@dyndns.org",
      gender: "Male",
      ip_address: "89.140.193.153",
    },
    {
      id: 32,
      first_name: "Alicea",
      last_name: "MacAdam",
      email: "amacadamv@dmoz.org",
      gender: "Female",
      ip_address: "228.40.125.203",
    },
    {
      id: 33,
      first_name: "Dudley",
      last_name: "Berwick",
      email: "dberwickw@artisteer.com",
      gender: "Male",
      ip_address: "146.255.216.82",
    },
    {
      id: 34,
      first_name: "Violante",
      last_name: "Jodlkowski",
      email: "vjodlkowskix@bizjournals.com",
      gender: "Female",
      ip_address: "80.232.165.187",
    },
    {
      id: 35,
      first_name: "Gradey",
      last_name: "Killock",
      email: "gkillocky@chronoengine.com",
      gender: "Male",
      ip_address: "122.36.181.5",
    },
    {
      id: 36,
      first_name: "Fitz",
      last_name: "Howels",
      email: "fhowelsz@dailymotion.com",
      gender: "Male",
      ip_address: "185.163.108.116",
    },
    {
      id: 37,
      first_name: "Gerri",
      last_name: "Endean",
      email: "gendean10@themeforest.net",
      gender: "Male",
      ip_address: "202.240.13.25",
    },
    {
      id: 38,
      first_name: "Whitaker",
      last_name: "Coad",
      email: "wcoad11@nature.com",
      gender: "Male",
      ip_address: "97.129.224.242",
    },
    {
      id: 39,
      first_name: "Putnem",
      last_name: "Chazotte",
      email: "pchazotte12@tuttocitta.it",
      gender: "Male",
      ip_address: "217.251.153.127",
    },
    {
      id: 40,
      first_name: "Max",
      last_name: "Strutz",
      email: "mstrutz13@ovh.net",
      gender: "Male",
      ip_address: "81.52.114.114",
    },
    {
      id: 41,
      first_name: "Cedric",
      last_name: "Spilsburie",
      email: "cspilsburie14@flavors.me",
      gender: "Male",
      ip_address: "63.49.6.48",
    },
    {
      id: 42,
      first_name: "Lorraine",
      last_name: "Gisby",
      email: "lgisby15@berkeley.edu",
      gender: "Female",
      ip_address: "226.50.103.156",
    },
    {
      id: 43,
      first_name: "Nanon",
      last_name: "Deares",
      email: "ndeares16@newsvine.com",
      gender: "Female",
      ip_address: "47.109.163.216",
    },
    {
      id: 44,
      first_name: "Brew",
      last_name: "Blacket",
      email: "bblacket17@dedecms.com",
      gender: "Male",
      ip_address: "153.111.11.119",
    },
    {
      id: 45,
      first_name: "Angel",
      last_name: "Joplin",
      email: "ajoplin18@hc360.com",
      gender: "Male",
      ip_address: "181.86.150.163",
    },
    {
      id: 46,
      first_name: "Theodor",
      last_name: "Bromhead",
      email: "tbromhead19@ask.com",
      gender: "Male",
      ip_address: "194.233.85.7",
    },
    {
      id: 47,
      first_name: "Gillian",
      last_name: "Stubs",
      email: "gstubs1a@sphinn.com",
      gender: "Female",
      ip_address: "167.140.181.95",
    },
    {
      id: 48,
      first_name: "Jaye",
      last_name: "Winders",
      email: "jwinders1b@forbes.com",
      gender: "Male",
      ip_address: "246.39.74.14",
    },
    {
      id: 49,
      first_name: "Nealson",
      last_name: "McDermott",
      email: "nmcdermott1c@xinhuanet.com",
      gender: "Male",
      ip_address: "27.140.21.218",
    },
    {
      id: 50,
      first_name: "Felicdad",
      last_name: "Likly",
      email: "flikly1d@answers.com",
      gender: "Female",
      ip_address: "9.122.21.70",
    },
    {
      id: 51,
      first_name: "Zared",
      last_name: "Gotcliff",
      email: "zgotcliff1e@diigo.com",
      gender: "Male",
      ip_address: "129.202.151.15",
    },
    {
      id: 52,
      first_name: "Solomon",
      last_name: "Hoys",
      email: "shoys1f@msn.com",
      gender: "Male",
      ip_address: "153.252.151.153",
    },
    {
      id: 53,
      first_name: "Homer",
      last_name: "Benham",
      email: "hbenham1g@bloglovin.com",
      gender: "Male",
      ip_address: "92.62.61.181",
    },
    {
      id: 54,
      first_name: "Raddy",
      last_name: "Menichi",
      email: "rmenichi1h@reddit.com",
      gender: "Male",
      ip_address: "117.61.170.133",
    },
    {
      id: 55,
      first_name: "Ludwig",
      last_name: "Showl",
      email: "lshowl1i@jalbum.net",
      gender: "Male",
      ip_address: "43.18.225.192",
    },
    {
      id: 56,
      first_name: "Jacquelyn",
      last_name: "Halbard",
      email: "jhalbard1j@issuu.com",
      gender: "Female",
      ip_address: "147.44.223.20",
    },
    {
      id: 57,
      first_name: "Mahmud",
      last_name: "Lantuffe",
      email: "mlantuffe1k@bloglovin.com",
      gender: "Male",
      ip_address: "134.244.146.35",
    },
    {
      id: 58,
      first_name: "Toni",
      last_name: "Burnand",
      email: "tburnand1l@dyndns.org",
      gender: "Female",
      ip_address: "234.220.63.5",
    },
    {
      id: 59,
      first_name: "Berni",
      last_name: "Sigg",
      email: "bsigg1m@nhs.uk",
      gender: "Female",
      ip_address: "57.92.6.95",
    },
    {
      id: 60,
      first_name: "Vivie",
      last_name: "Cockton",
      email: "vcockton1n@oakley.com",
      gender: "Female",
      ip_address: "104.235.81.159",
    },
    {
      id: 61,
      first_name: "Derril",
      last_name: "Causby",
      email: "dcausby1o@fema.gov",
      gender: "Male",
      ip_address: "45.149.132.150",
    },
    {
      id: 62,
      first_name: "Harlan",
      last_name: "Leport",
      email: "hleport1p@example.com",
      gender: "Male",
      ip_address: "172.54.205.4",
    },
    {
      id: 63,
      first_name: "Casper",
      last_name: "O'Bradain",
      email: "cobradain1q@answers.com",
      gender: "Male",
      ip_address: "182.109.242.195",
    },
    {
      id: 64,
      first_name: "Rice",
      last_name: "Duffill",
      email: "rduffill1r@toplist.cz",
      gender: "Male",
      ip_address: "36.156.79.131",
    },
    {
      id: 65,
      first_name: "Adara",
      last_name: "Duthy",
      email: "aduthy1s@newyorker.com",
      gender: "Female",
      ip_address: "30.108.85.166",
    },
    {
      id: 66,
      first_name: "Marin",
      last_name: "Fiddymont",
      email: "mfiddymont1t@fda.gov",
      gender: "Female",
      ip_address: "227.210.144.218",
    },
    {
      id: 67,
      first_name: "Alwin",
      last_name: "O'Loughane",
      email: "aoloughane1u@squidoo.com",
      gender: "Male",
      ip_address: "47.231.208.120",
    },
    {
      id: 68,
      first_name: "Jacinta",
      last_name: "Magnus",
      email: "jmagnus1v@bluehost.com",
      gender: "Female",
      ip_address: "0.227.22.124",
    },
    {
      id: 69,
      first_name: "Bradney",
      last_name: "Such",
      email: "bsuch1w@smh.com.au",
      gender: "Male",
      ip_address: "114.96.30.33",
    },
    {
      id: 70,
      first_name: "Raviv",
      last_name: "Jahnig",
      email: "rjahnig1x@ibm.com",
      gender: "Male",
      ip_address: "126.73.140.70",
    },
    {
      id: 71,
      first_name: "Quinn",
      last_name: "Belden",
      email: "qbelden1y@sbwire.com",
      gender: "Male",
      ip_address: "255.94.49.19",
    },
    {
      id: 72,
      first_name: "Lorie",
      last_name: "Myles",
      email: "lmyles1z@boston.com",
      gender: "Female",
      ip_address: "191.106.50.229",
    },
    {
      id: 73,
      first_name: "Karen",
      last_name: "Bond",
      email: "kbond20@columbia.edu",
      gender: "Female",
      ip_address: "240.22.48.186",
    },
    {
      id: 74,
      first_name: "Jobi",
      last_name: "Corley",
      email: "jcorley21@mozilla.org",
      gender: "Female",
      ip_address: "130.147.137.73",
    },
    {
      id: 75,
      first_name: "Cyndi",
      last_name: "Lacase",
      email: "clacase22@ebay.co.uk",
      gender: "Female",
      ip_address: "211.184.241.39",
    },
    {
      id: 76,
      first_name: "Erminia",
      last_name: "Clatworthy",
      email: "eclatworthy23@google.it",
      gender: "Female",
      ip_address: "96.21.232.10",
    },
    {
      id: 77,
      first_name: "Tait",
      last_name: "Achromov",
      email: "tachromov24@imageshack.us",
      gender: "Male",
      ip_address: "94.99.231.147",
    },
    {
      id: 78,
      first_name: "Nathanael",
      last_name: "Kohler",
      email: "nkohler25@github.com",
      gender: "Male",
      ip_address: "67.216.132.42",
    },
    {
      id: 79,
      first_name: "Annabal",
      last_name: "Tommei",
      email: "atommei26@sourceforge.net",
      gender: "Female",
      ip_address: "113.71.92.202",
    },
    {
      id: 80,
      first_name: "Bobbee",
      last_name: "Pendock",
      email: "bpendock27@dmoz.org",
      gender: "Female",
      ip_address: "213.213.119.15",
    },
    {
      id: 81,
      first_name: "Delmer",
      last_name: "Keymer",
      email: "dkeymer28@chron.com",
      gender: "Male",
      ip_address: "71.211.139.124",
    },
    {
      id: 82,
      first_name: "Bryna",
      last_name: "Merricks",
      email: "bmerricks29@scribd.com",
      gender: "Female",
      ip_address: "1.100.8.115",
    },
    {
      id: 83,
      first_name: "Ivory",
      last_name: "Cann",
      email: "icann2a@dedecms.com",
      gender: "Female",
      ip_address: "100.233.123.251",
    },
    {
      id: 84,
      first_name: "Zenia",
      last_name: "Cornewall",
      email: "zcornewall2b@businesswire.com",
      gender: "Female",
      ip_address: "32.101.169.80",
    },
    {
      id: 85,
      first_name: "Neron",
      last_name: "Messent",
      email: "nmessent2c@intel.com",
      gender: "Male",
      ip_address: "122.109.145.156",
    },
    {
      id: 86,
      first_name: "Bendicty",
      last_name: "Ivens",
      email: "bivens2d@privacy.gov.au",
      gender: "Male",
      ip_address: "24.120.203.175",
    },
    {
      id: 87,
      first_name: "Nigel",
      last_name: "Nuss",
      email: "nnuss2e@hc360.com",
      gender: "Male",
      ip_address: "153.159.34.143",
    },
    {
      id: 88,
      first_name: "Fedora",
      last_name: "Boyfield",
      email: "fboyfield2f@dot.gov",
      gender: "Female",
      ip_address: "16.169.230.191",
    },
    {
      id: 89,
      first_name: "Corbet",
      last_name: "Jina",
      email: "cjina2g@artisteer.com",
      gender: "Male",
      ip_address: "6.104.247.249",
    },
    {
      id: 90,
      first_name: "Audre",
      last_name: "Saltern",
      email: "asaltern2h@yellowpages.com",
      gender: "Female",
      ip_address: "80.188.217.167",
    },
    {
      id: 91,
      first_name: "Bruis",
      last_name: "Hans",
      email: "bhans2i@cyberchimps.com",
      gender: "Male",
      ip_address: "93.57.235.239",
    },
    {
      id: 92,
      first_name: "Sisely",
      last_name: "Guitel",
      email: "sguitel2j@about.me",
      gender: "Female",
      ip_address: "127.77.194.119",
    },
    {
      id: 93,
      first_name: "Marylynne",
      last_name: "Yurshev",
      email: "myurshev2k@yale.edu",
      gender: "Female",
      ip_address: "151.216.55.234",
    },
    {
      id: 94,
      first_name: "Goober",
      last_name: "Escritt",
      email: "gescritt2l@squidoo.com",
      gender: "Male",
      ip_address: "154.100.216.53",
    },
    {
      id: 95,
      first_name: "Rudiger",
      last_name: "Sachno",
      email: "rsachno2m@diigo.com",
      gender: "Male",
      ip_address: "152.147.252.242",
    },
    {
      id: 96,
      first_name: "Tanney",
      last_name: "Crispe",
      email: "tcrispe2n@unblog.fr",
      gender: "Male",
      ip_address: "237.221.180.199",
    },
    {
      id: 97,
      first_name: "Phil",
      last_name: "Brunotti",
      email: "pbrunotti2o@admin.ch",
      gender: "Female",
      ip_address: "149.204.170.167",
    },
    {
      id: 98,
      first_name: "Ingram",
      last_name: "Lundberg",
      email: "ilundberg2p@ameblo.jp",
      gender: "Male",
      ip_address: "139.51.6.199",
    },
    {
      id: 99,
      first_name: "Leontyne",
      last_name: "Baines",
      email: "lbaines2q@google.ru",
      gender: "Female",
      ip_address: "73.239.114.35",
    },
    {
      id: 100,
      first_name: "Byrle",
      last_name: "Roubay",
      email: "broubay2r@privacy.gov.au",
      gender: "Male",
      ip_address: "3.59.174.11",
    },
  ];
};

export default new Vuex.Store({
  state: {

    movies: movies(),

    filters: {
      query: '',
      available: true
    }

  },

  mutations: {

    SET_QUERY(state, query) {
      state.filters.query = query;
    },

    SET_AVAILABLE(state) {
      state.filters.available = !state.filters.available;
    }

  },

  getters: {

  },

  actions: {},
  modules: {},
});
